version: "3"
services:
  myapp:
    container_name: myapp
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/go/src/app/
      - ./${GO_MOD}:/go/src/app/go.mod
      - ../mypackage:/go/src/mypackage
    restart: unless-stopped
